#logging:
#  level:
#    org:
#      springframework:
#        web: DEBUG
#spring:
#  application:
#    name: springboot_2
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: Your Password
#    url: jdbc:mysql://localhost:3306/department_springboot_db
#    username: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true